# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Realm-Cocoapods' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'ScrollableGraphView', '~> 4.0'
pod 'RealmSwift'
  # Pods for Realm-Cocoapods

end
